apiVersion: v1
kind: Service
metadata:
  name: headless-svc
spec:
  clusterIP: None # clusterIP must be None to create a headless service
  selector:
    job-name: jax-hello-world # must match Job name
---
apiVersion: batch/v1
kind: Job
metadata:
  name: jax-hello-world
spec:
  completions: 1
  parallelism: 1
  completionMode: Indexed
  template:
    spec:
      subdomain: headless-svc
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-tesla-t4
      restartPolicy: Never
      containers:
      - name: 'jax-worker'
        image: 'gcr.io/jk-mlops-dev/jax-sandbox'
        command: ["python"]
        args:
        - train.py
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            cpu: "8"
            memory: "30Gi"    
        env:
        - name: NUM_PROCESSES
          value: "1"

